# action.yml
name: 'OPC UA C/C++ Base Server'
description: 'starts a base server of a NodeSet2.xml file'

inputs:
# the current configuration does not allow to change the port
  # default-opc-port:  
  #   description: 'The default port to publish, if the server needs to be exposed to the host interface'
  #   required: false
  #   default: '4840'
  service-network:  
    description: 'the custom docker network to run opc commands to'
    required: false
    default: ''
  lds-version:  
    description: 'the build version to choose from the configured source repository'
    required: false
    default: 'master'

outputs:
  cid:
    description: Container ID of the new service container 
    value: ${{ steps.exec.outputs.cid }}

runs:
  using: composite
  steps:
    - name: Build
      shell: bash
      working-directory: ${{ github.action_path }}
      env: 
        UA_LDS_VERSION: ${{ inputs.lds-version }}
      run: |
        echo "::group::Building Image for C/C++ OPC Server"
        ./docker-build.sh
        echo "::endgroup::"

    - name: Check the networking configuration for the docker service 
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        echo "::group::Setting up Network Configuration for the local runner"
        ./network-setup.sh ${{ inputs.service-network }}
        echo "::endgroup::"

    - name: Run the service container 
      shell: bash
      id: exec
      working-directory: ${{ github.action_path }}
      env: 
        UA_LDS_VERSION: ${{ inputs.lds-version }}
      run: |
        echo "::group::Starting the C/C++ Server in the background"
        ./docker-run.sh 
        echo "::endgroup::"
