services:

  # as a reminder: redis commander currently only works on x86, not on ARM
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
        #networks:
        #- redis-network
        #depends_on:
        #- redis
